{{- if .Values.neo4j.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ccns.fullname" . }}-neopwd
  labels:
    app: {{ template "ccns.name" . }}
    chart: {{ template "ccns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.neo4j.password | b64enc | quote }}
{{- end }}
