{{- if .Values.cassandra.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cpms.fullname" . }}-casspwd
  labels:
    app: {{ template "cpms.name" . }}
    chart: {{ template "cpms.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  password: {{ .Values.cassandra.password | b64enc | quote }}
{{- end }}
  
